### ISSUE TITLE
Player id always return 0?

### ISSUE THREAD

**Issue by pede** [yannickcr/SourceQuery#1]
Why do the player id always return 0?

Example of my GetPlayers array:

 Array
 (
     [0] => Array
        (
            [Id] => 0
            [Name] => SwagMaster08
            [Frags] => 1
            [Time] => 4344
            [TimeF] => 01:12:24
        )

```
[1] => Array
    (
        [Id] => 0
        [Name] => Olaf
        [Frags] => 0
        [Time] => 4332
        [TimeF] => 01:12:12
    )

[2] => Array
    (
        [Id] => 0
        [Name] => Jesper
        [Frags] => 0
        [Time] => 3951
        [TimeF] => 01:05:51
    )

[3] => Array
    (
        [Id] => 0
        [Name] => Keps
        [Frags] => 0
        [Time] => 1289
        [TimeF] => 21:29
    )
```

)

**Comment by yannickcr** [comment]
Apparently the gameserver always return 0 for the PlayerID. This is part of the protocol and we can't really do anything to fix this.
